### PR TITLE
Use smart-table library to implement sorting and pagination

### PR DESCRIPTION
**Pull request by waynelai614**
Use Angular table library (smart-table), and combine some commits (fixed the Travis issue#N)

### CODE REVIEW

**Comment by CYBAI** [comment]
@waynelai614 Please change the PR title to make reviewers be able to understand the goal directly from the title. BTW, when you use `#` with number, it will refer to the number of issue or PR; therefore, please don't use `#X` in commits or comments if you're not going to refer to another issue or PR when you're using GitHub.

**Comment by waynelai614** [comment]
@CYBAI done.

**Comment by man27382210** [comment]
@waynelai614 
Please fix the conflicts.

**Comment by waynelai614** [comment]
@man27382210 
Done. Please review!

**Pull request merged**
